name: Deploy

on: push

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build image
        run: docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/weshareus-back:latest

      - name: Docker login
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/weshareus-back:latest

      - name: SSH remote and Run Docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.REMOTE_KEY }}
          port: 22
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/weshareus-back:latest
            docker stop weshareus-back
            docker rm weshareus-back
            docker run --restart=unless-stopped --add-host=host.docker.internal:host-gateway -d -p 8080:8080 --name weshareus-back ${{ secrets.DOCKERHUB_USERNAME }}/weshareus-back:latest
            docker rmi $(docker images -f "dangling=true" -q)
            echo ">hello"